# Generated by Django 5.1.1 on 2024-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_app', '0002_rename_quaetionlike_questionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
