# Generated by Django 4.2.17 on 2024-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme_app', '0003_answer_is_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to=''),
        ),
    ]
